version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: task_manager_db
      POSTGRES_USER: trump
      POSTGRES_PASSWORD: not_harris
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
