- name: Update apt packages
  apt:
    update_cache: yes

- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: yes

- name: Add user to the docker group
  become: yes
  user:
    name: debian
    groups: docker
    append: yes