apiVersion: v1
kind: Service

metadata:
  # the name of the service, used for referencing within the cluster
  name: postgres-service

spec:
  # specifies the pods that this service targets, based on labels
  selector:
    app: postgres

  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

  type: ClusterIP
