# CONFIGURING A DEPLOYMENT FOR THE FRONTEND APPLICATION
apiVersion: apps/v1
kind: Deployment

metadata:
  # the name of the deployment
  name: frontend-deployment

spec:
  replicas: 2

  # specifies how the deployment identifies pods it manages
  selector:
    matchLabels:
      app: frontend

  # describes the template for the pods created by this deployment
  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:

          # setting up the container to run
        - name: frontend
          image: osklot12/svelte-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: VITE_API_BASE_URL
              value: "http://backend-service/api"

          # setting up a readiness probe
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          # setting up a liveness probe
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          # resource requests and limits
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "250m"
