# development configuration
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/tomorrow_db
    username: trump
    password: not_harris
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  management:
    endpoints:
      web:
        exposure:
          include: health
    endpoint:
      health:
        show-details: always