- name: Update apt packages
  apt:
    update_cache: yes

- name: Install PostgreSQL
  apt:
    name: postgresql
    state: present

- name: Ensure PostgreSQL service is running
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Get the PostgreSQL version directory
  shell: "ls /etc/postgresql | sort -V | tail -n 1"
  register: postgresql_version_result
  become: yes

- name: Set PostgreSQL version fact
  set_fact:
    postgresql_version: "{{ postgresql_version_result.stdout }}"

- name: Ensure PostgreSQL is configured to listen on all IPs
  lineinfile:
    path: "/etc/postgresql/{{ postgresql_version }}/main/postgresql.conf"
    regexp: '^#?(listen_addresses\s*=\s*)\S+'
    line: "listen_addresses = '*'"
    state: present
  notify: Restart PostgreSQL
  become: yes

- name: Allow connections from all IPs
  lineinfile:
    path: "/etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf"
    line: "host    all             all             0.0.0.0/0               md5"
    state: present
  notify: Restart PostgreSQL
  become: yes

- name: Create a PostgreSQL user
  postgresql_user:
    name: trump
    password: not_harris
    priv: "ALL"
  become: yes
  become_user: postgres

- name: Create a PostgreSQL database
  postgresql_db:
    name: tomorrow_db
    owner: trump
  become: yes
  become_user: postgres
