apiVersion: v1
kind: Service

metadata:
  # the name of the service, used for referencing within the cluster
  name: frontend-service
  namespace: default
spec:
  # specifies the pods that this service targets, based on labels
  selector:
    app: frontend

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

  type: LoadBalancer
  loadBalancerIP: "34.88.62.168"