name: Build, Scan, and Push Containers

on:
  workflow_run:
    workflows:
      - Unit Tests
    types:
      - completed

jobs:
  build-scan-and-push-containers:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 8: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 9: Build the Svelte frontend container image
      - name: Build Svelte app container
        run: |
          docker build -t osklot12/svelte-frontend:latest ./frontend

      # Step 10: Build the Spring backend container image
      - name: Build Spring Boot backend image
        run: |
          docker build -t osklot12/spring-backend:latest ./backend

      # Step 11: Scan Svelte frontend image for vulnerabilities
      - name: Scan Svelte app container
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: osklot12/svelte-frontend:latest

      # Step 12: Scan Spring backend image for vulnerabilities
      - name: Scan Spring Boot backend container
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: osklot12/spring-backend:latest

      # Step 13: Push the Svelte frontend Docker image
      - name: Push Svelte frontend Docker image
        run: |
          docker push osklot12/svelte-frontend:latest

      # Step 14: Push the Spring backend Docker image
      - name: Push Spring backend Docker image
        run: |
          docker push osklot12/spring-backend:latest
